name: talabat
repository: https://github.com/talabat-dhme/talabat-mobile-app-flutter

command:

  bootstrap:
    environment:
      sdk: ">=3.4.4 <4.0.0"
      flutter: ">=3.22.3"

    dependencies:
      
      cli_util: 0.4.1
      
      melos: 6.3.1
      flutter_bloc: 9.0.0
      firebase_core: 3.10.0
      firebase_crashlytics: 4.3.0

packages:
  - .
  - packages/**

ide:
  intellij: false
  vscode: false
  androidStudio: false
